package composite

enum class NodeType {
  OPERATION,
  LITERAL,
  IDENTIFIER,
  DATA_TYPE,
  METHOD_CALL,
  ARGUMENTS,
    METHOD_NAME,
    DECLARATION,
    ASSIGNATION,
    ASSIGNATION_DECLARATION
}