name: Continuos Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  cd:
    uses: group-5-ingsis/workflows/.github/workflows/cd-packages.yml@main

