name: Continuos Delivery

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: group-5-ingsis/workflows/.github/workflows/cd-packages.yml@main